name: run main.py

on:
  schedule:
    - cron: '0 0 * * *' # run every day at 00:00 UTC
  workflow_dispatch: # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          TOKEN_UR_ALWAYS_MY: ${{ secrets.TOKEN_UR_ALWAYS_MY }}
          TOKEN_OPTIMUM_PRIDE: ${{ secrets.TOKEN_OPTIMUM_PRIDE }}
          URL_UR_ALWAYS_MY: ${{ secrets.URL_UR_ALWAYS_MY }}
          URL_OPTIMUM_PRIDE: ${{ secrets.URL_OPTIMUM_PRIDE }}
        run: python3 main.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # auto generated github token
          branch: main 